### ISSUE TITLE
P1 data from Landis+Gyr e360 Sigle phase

### ISSUE THREAD

**Issue by Fjuxx** [SmartEVSE/smartevse#22] opened 2020-01-05 18:26 UTC
I discovered that there is a problem with the Sensorbox 2 with a Landis+Gyr e360 smart meter when using a single phase.

the smart evse seems to not balance the load at all even when it is exceeding the set mains limit.
when the CT clips are connected it does work as expected.

I've enabled debug rows 2232 and 2233 and uploaded the new firmware to the smart evse to see what is happening.

here is a log of everything with the P1 data:
````
STATE: A Error: 2 StartCurrent: -4 ImeasuredNegative: 0.0 A ChargeDelay: 0 SolarStopTimer: 0 NoCurrent: 0 Imeas: 0.0 A IsetBalanced: 21.0 A L1: 6.8 A L2: 34028235080000000000000000000000000000.0 A L3: 34028235080000000000000000000000000000.0 A Isum: 6.8 A
Cable limit: 16A  Max: 16A
STATE A->B
STATE: B Error: 0 StartCurrent: -4 ImeasuredNegative: 0.0 A ChargeDelay: 0 SolarStopTimer: 0 NoCurrent: 0 Imeas: 0.0 A IsetBalanced: 26.0 A L1: 6.8 A L2: 34028235080000000000000000000000000000.0 A L3: 34028235080000000000000000000000000000.0 A Isum: 6.8 A
Imeasured:0.0 A IsetBalanced:16.0 A Baseload:0.0 A EVSE0[2]:16.0 A EVSE1[0]:0.0 A EVSE2[0]:0.0 A EVSE3[0]:0.0 A
STATE B->C
Imeasured:0.0 A IsetBalanced:16.0 A Baseload:0.0 A EVSE0[2]:16.0 A EVSE1[0]:0.0 A EVSE2[0]:0.0 A EVSE3[0]:0.0 A
STATE: C Error: 0 StartCurrent: -4 ImeasuredNegative: 0.0 A ChargeDelay: 0 SolarStopTimer: 0 NoCurrent: 0 Imeas: 0.0 A IsetBalanced: 16.0 A L1: 6.9 A L2: 34028235080000000000000000000000000000.0 A L3: 34028235080000000000000000000000000000.0 A Isum: 6.9 A
Imeasured:0.0 A IsetBalanced:16.0 A Baseload:0.0 A EVSE0[2]:16.0 A EVSE1[0]:0.0 A EVSE2[0]:0.0 A EVSE3[0]:0.0 A
STATE: C Error: 0 StartCurrent: -4 ImeasuredNegative: 0.0 A ChargeDelay: 0 SolarStopTimer: 0 NoCurrent: 0 Imeas: 0.0 A IsetBalanced: 16.0 A L1: 7.1 A L2: 34028235080000000000000000000000000000.0 A L3: 34028235080000000000000000000000000000.0 A Isum: 7.1 A
Imeasured:0.0 A IsetBalanced:16.0 A Baseload:0.0 A EVSE0[2]:16.0 A EVSE1[0]:0.0 A EVSE2[0]:0.0 A EVSE3[0]:0.0 A
STATE: C Error: 0 StartCurrent: -4 ImeasuredNegative: 0.0 A ChargeDelay: 0 SolarStopTimer: 0 NoCurrent: 0 Imeas: 0.0 A IsetBalanced: 16.0 A L1: 8.9 A L2: 34028235080000000000000000000000000000.0 A L3: 34028235080000000000000000000000000000.0 A Isum: 8.9 A
Imeasured:0.0 A IsetBalanced:16.0 A Baseload:0.0 A EVSE0[2]:16.0 A EVSE1[0]:0.0 A EVSE2[0]:0.0 A EVSE3[0]:0.0 A
STATE: C Error: 0 StartCurrent: -4 ImeasuredNegative: 0.0 A ChargeDelay: 0 SolarStopTimer: 0 NoCurrent: 0 Imeas: 0.0 A IsetBalanced: 16.0 A L1: 13.6 A L2: 34028235080000000000000000000000000000.0 A L3: 34028235080000000000000000000000000000.0 A Isum: 13.6 A
Imeasured:0.0 A IsetBalanced:16.0 A Baseload:0.0 A EVSE0[2]:16.0 A EVSE1[0]:0.0 A EVSE2[0]:0.0 A EVSE3[0]:0.0 A
STATE: C Error: 0 StartCurrent: -4 ImeasuredNegative: 0.0 A ChargeDelay: 0 SolarStopTimer: 0 NoCurrent: 0 Imeas: 0.0 A IsetBalanced: 16.0 A L1: 13.4 A L2: 34028235080000000000000000000000000000.0 A L3: 34028235080000000000000000000000000000.0 A Isum: 13.4 A
Imeasured:0.0 A IsetBalanced:16.0 A Baseload:0.0 A EVSE0[2]:16.0 A EVSE1[0]:0.0 A EVSE2[0]:0.0 A EVSE3[0]:0.0 A
STATE: C Error: 0 StartCurrent: -4 ImeasuredNegative: 0.0 A ChargeDelay: 0 SolarStopTimer: 0 NoCurrent: 0 Imeas: 0.0 A IsetBalanced: 16.0 A L1: 14.2 A L2: 34028235080000000000000000000000000000.0 A L3: 34028235080000000000000000000000000000.0 A Isum: 14.2 A
Imeasured:0.0 A IsetBalanced:16.0 A Baseload:0.0 A EVSE0[2]:16.0 A EVSE1[0]:0.0 A EVSE2[0]:0.0 A EVSE3[0]:0.0 A
STATE: C Error: 0 StartCurrent: -4 ImeasuredNegative: 0.0 A ChargeDelay: 0 SolarStopTimer: 0 NoCurrent: 0 Imeas: 0.0 A IsetBalanced: 16.0 A L1: 21.6 A L2: 34028235080000000000000000000000000000.0 A L3: 34028235080000000000000000000000000000.0 A Isum: 21.6 A
Imeasured:0.0 A IsetBalanced:16.0 A Baseload:0.0 A EVSE0[2]:16.0 A EVSE1[0]:0.0 A EVSE2[0]:0.0 A EVSE3[0]:0.0 A
STATE: C Error: 0 StartCurrent: -4 ImeasuredNegative: 0.0 A ChargeDelay: 0 SolarStopTimer: 0 NoCurrent: 0 Imeas: 0.0 A IsetBalanced: 16.0 A L1: 21.7 A L2: 34028235080000000000000000000000000000.0 A L3: 34028235080000000000000000000000000000.0 A Isum: 21.7 A
Imeasured:0.0 A IsetBalanced:16.0 A Baseload:0.0 A EVSE0[2]:16.0 A EVSE1[0]:0.0 A EVSE2[0]:0.0 A EVSE3[0]:0.0 A
STATE: C Error: 0 StartCurrent: -4 ImeasuredNegative: 0.0 A ChargeDelay: 0 SolarStopTimer: 0 NoCurrent: 0 Imeas: 0.0 A IsetBalanced: 16.0 A L1: 21.4 A L2: 34028235080000000000000000000000000000.0 A L3: 34028235080000000000000000000000000000.0 A Isum: 21.4 A
Imeasured:0.0 A IsetBalanced:16.0 A Baseload:0.0 A EVSE0[2]:16.0 A EVSE1[0]:0.0 A EVSE2[0]:0.0 A EVSE3[0]:0.0 A
STATE: C Error: 0 StartCurrent: -4 ImeasuredNegative: 0.0 A ChargeDelay: 0 SolarStopTimer: 0 NoCurrent: 0 Imeas: 0.0 A IsetBalanced: 16.0 A L1: 21.6 A L2: 34028235080000000000000000000000000000.0 A L3: 34028235080000000000000000000000000000.0 A Isum: 21.6 A
Imeasured:0.0 A IsetBalanced:16.0 A Baseload:0.0 A EVSE0[2]:16.0 A EVSE1[0]:0.0 A EVSE2[0]:0.0 A EVSE3[0]:0.0 A
STATE: C Error: 0 StartCurrent: -4 ImeasuredNegative: 0.0 A ChargeDelay: 0 SolarStopTimer: 0 NoCurrent: 0 Imeas: 0.0 A IsetBalanced: 16.0 A L1: 20.7 A L2: 34028235080000000000000000000000000000.0 A L3: 34028235080000000000000000000000000000.0 A Isum: 20.7 A
Imeasured:0.0 A IsetBalanced:16.0 A Baseload:0.0 A EVSE0[2]:16.0 A EVSE1[0]:0.0 A EVSE2[0]:0.0 A EVSE3[0]:0.0 A
STATE: C Error: 0 StartCurrent: -4 ImeasuredNegative: 0.0 A ChargeDelay: 0 SolarStopTimer: 0 NoCurrent: 0 Imeas: 0.0 A IsetBalanced: 16.0 A L1: 20.9 A L2: 34028235080000000000000000000000000000.0 A L3: 34028235080000000000000000000000000000.0 A Isum: 20.9 A
Imeasured:0.0 A IsetBalanced:16.0 A Baseload:0.0 A EVSE0[2]:16.0 A EVSE1[0]:0.0 A EVSE2[0]:0.0 A EVSE3[0]:0.0 A
STATE: C Error: 0 StartCurrent: -4 ImeasuredNegative: 0.0 A ChargeDelay: 0 SolarStopTimer: 0 NoCurrent: 0 Imeas: 0.0 A IsetBalanced: 16.0 A L1: 22.0 A L2: 34028235080000000000000000000000000000.0 A L3: 34028235080000000000000000000000000000.0 A Isum: 22.0 A
Imeasured:0.0 A IsetBalanced:16.0 A Baseload:0.0 A EVSE0[2]:16.0 A EVSE1[0]:0.0 A EVSE2[0]:0.0 A EVSE3[0]:0.0 A
STATE: C Error: 0 StartCurrent: -4 ImeasuredNegative: 0.0 A ChargeDelay: 0 SolarStopTimer: 0 NoCurrent: 0 Imeas: 0.0 A IsetBalanced: 16.0 A L1: 21.5 A L2: 34028235080000000000000000000000000000.0 A L3: 34028235080000000000000000000000000000.0 A Isum: 21.5 A
````

following detaching the P1 and connecting the CT clip:
````
Imeasured:0.0 A IsetBalanced:16.0 A Baseload:0.0 A EVSE0[2]:16.0 A EVSE1[0]:0.0 A EVSE2[0]:0.0 A EVSE3[0]:0.0 A
STATE: C Error: 0 StartCurrent: -4 ImeasuredNegative: 0.0 A ChargeDelay: 0 SolarStopTimer: 0 NoCurrent: 0 Imeas: 0.0 A IsetBalanced: 16.0 A L1: 0.0 A L2: 0.0 A L3: -0.0 A Isum: 0.0 A
Imeasured:0.0 A IsetBalanced:16.0 A Baseload:0.0 A EVSE0[2]:16.0 A EVSE1[0]:0.0 A EVSE2[0]:0.0 A EVSE3[0]:0.0 A
STATE: C Error: 0 StartCurrent: -4 ImeasuredNegative: 0.0 A ChargeDelay: 0 SolarStopTimer: 0 NoCurrent: 0 Imeas: 0.0 A IsetBalanced: 16.0 A L1: -0.0 A L2: -0.0 A L3: 0.0 A Isum: -0.0 A
Imeasured:0.0 A IsetBalanced:16.0 A Baseload:0.0 A EVSE0[2]:16.0 A EVSE1[0]:0.0 A EVSE2[0]:0.0 A EVSE3[0]:0.0 A
STATE: C Error: 0 StartCurrent: -4 ImeasuredNegative: 0.0 A ChargeDelay: 0 SolarStopTimer: 0 NoCurrent: 0 Imeas: 0.0 A IsetBalanced: 16.0 A L1: -0.0 A L2: 0.0 A L3: -0.0 A Isum: -0.0 A
Imeasured:0.0 A IsetBalanced:16.0 A Baseload:0.0 A EVSE0[2]:16.0 A EVSE1[0]:0.0 A EVSE2[0]:0.0 A EVSE3[0]:0.0 A
STATE: C Error: 0 StartCurrent: -4 ImeasuredNegative: 0.0 A ChargeDelay: 0 SolarStopTimer: 0 NoCurrent: 0 Imeas: 0.0 A IsetBalanced: 16.0 A L1: 0.0 A L2: 0.0 A L3: 0.0 A Isum: 0.0 A
Imeasured:0.0 A IsetBalanced:16.0 A Baseload:0.0 A EVSE0[2]:16.0 A EVSE1[0]:0.0 A EVSE2[0]:0.0 A EVSE3[0]:0.0 A
STATE: C Error: 0 StartCurrent: -4 ImeasuredNegative: 0.0 A ChargeDelay: 0 SolarStopTimer: 0 NoCurrent: 0 Imeas: 0.0 A IsetBalanced: 16.0 A L1: 0.0 A L2: -0.0 A L3: -0.0 A Isum: 0.0 A
Imeasured:0.0 A IsetBalanced:16.0 A Baseload:0.0 A EVSE0[2]:16.0 A EVSE1[0]:0.0 A EVSE2[0]:0.0 A EVSE3[0]:0.0 A
STATE: C Error: 0 StartCurrent: -4 ImeasuredNegative: 0.0 A ChargeDelay: 0 SolarStopTimer: 0 NoCurrent: 0 Imeas: 0.0 A IsetBalanced: 16.0 A L1: -0.0 A L2: -0.0 A L3: 0.0 A Isum: 0.0 A
Imeasured:21.0 A IsetBalanced:15.0 A Baseload:0.0 A EVSE0[2]:15.0 A EVSE1[0]:0.0 A EVSE2[0]:0.0 A EVSE3[0]:0.0 A
STATE: C Error: 0 StartCurrent: -4 ImeasuredNegative: 0.0 A ChargeDelay: 0 SolarStopTimer: 0 NoCurrent: 0 Imeas: 21.0 A IsetBalanced: 15.0 A L1: 21.1 A L2: 0.0 A L3: 0.0 A Isum: 21.1 A
Imeasured:18.9 A IsetBalanced:15.2 A Baseload:0.0 A EVSE0[2]:15.2 A EVSE1[0]:0.0 A EVSE2[0]:0.0 A EVSE3[0]:0.0 A
STATE: C Error: 0 StartCurrent: -4 ImeasuredNegative: 0.0 A ChargeDelay: 0 SolarStopTimer: 0 NoCurrent: 0 Imeas: 18.9 A IsetBalanced: 15.2 A L1: 19.0 A L2: -0.0 A L3: -0.0 A Isum: 19.0 A
Imeasured:18.6 A IsetBalanced:15.5 A Baseload:0.0 A EVSE0[2]:15.5 A EVSE1[0]:0.0 A EVSE2[0]:0.0 A EVSE3[0]:0.0 A
STATE: C Error: 0 StartCurrent: -4 ImeasuredNegative: 0.0 A ChargeDelay: 0 SolarStopTimer: 0 NoCurrent: 0 Imeas: 18.6 A IsetBalanced: 15.5 A L1: 18.6 A L2: 0.0 A L3: 0.0 A Isum: 18.6 A
Imeasured:18.4 A IsetBalanced:15.9 A Baseload:0.0 A EVSE0[2]:15.9 A EVSE1[0]:0.0 A EVSE2[0]:0.0 A EVSE3[0]:0.0 A
STATE: C Error: 0 StartCurrent: -4 ImeasuredNegative: 0.0 A ChargeDelay: 0 SolarStopTimer: 0 NoCurrent: 0 Imeas: 18.4 A IsetBalanced: 15.9 A L1: 18.4 A L2: 0.0 A L3: -0.0 A Isum: 18.4 A
Imeasured:20.0 A IsetBalanced:15.9 A Baseload:0.0 A EVSE0[2]:15.9 A EVSE1[0]:0.0 A EVSE2[0]:0.0 A EVSE3[0]:0.0 A
STATE: C Error: 0 StartCurrent: -4 ImeasuredNegative: 0.0 A ChargeDelay: 0 SolarStopTimer: 0 NoCurrent: 0 Imeas: 20.0 A IsetBalanced: 15.9 A L1: 20.1 A L2: 0.0 A L3: -0.0 A Isum: 20.1 A
Imeasured:20.8 A IsetBalanced:15.1 A Baseload:0.0 A EVSE0[2]:15.1 A EVSE1[0]:0.0 A EVSE2[0]:0.0 A EVSE3[0]:0.0 A
STATE: C Error: 0 StartCurrent: -4 ImeasuredNegative: 0.0 A ChargeDelay: 0 SolarStopTimer: 0 NoCurrent: 0 Imeas: 20.8 A IsetBalanced: 15.1 A L1: 20.8 A L2: 0.0 A L3: -0.0 A Isum: 20.8 A
Imeasured:20.9 A IsetBalanced:14.2 A Baseload:0.0 A EVSE0[2]:14.2 A EVSE1[0]:0.0 A EVSE2[0]:0.0 A EVSE3[0]:0.0 A
STATE: C Error: 0 StartCurrent: -4 ImeasuredNegative: 0.0 A ChargeDelay: 0 SolarStopTimer: 0 NoCurrent: 0 Imeas: 20.9 A IsetBalanced: 14.2 A L1: 21.0 A L2: -0.0 A L3: -0.0 A Isum: 21.0 A
Imeasured:20.5 A IsetBalanced:13.7 A Baseload:0.0 A EVSE0[2]:13.7 A EVSE1[0]:0.0 A EVSE2[0]:0.0 A EVSE3[0]:0.0 A
STATE: C Error: 0 StartCurrent: -4 ImeasuredNegative: 0.0 A ChargeDelay: 0 SolarStopTimer: 0 NoCurrent: 0 Imeas: 20.5 A IsetBalanced: 13.7 A L1: 20.6 A L2: -0.0 A L3: 0.0 A Isum: 20.6 A
Imeasured:19.9 A IsetBalanced:13.7 A Baseload:0.0 A EVSE0[2]:13.7 A EVSE1[0]:0.0 A EVSE2[0]:0.0 A EVSE3[0]:0.0 A
STATE: C Error: 0 StartCurrent: -4 ImeasuredNegative: 0.0 A ChargeDelay: 0 SolarStopTimer: 0 NoCurrent: 0 Imeas: 19.9 A IsetBalanced: 13.7 A L1: 19.9 A L2: 0.0 A L3: -0.0 A Isum: 19.9 A
Imeasured:19.4 A IsetBalanced:13.8 A Baseload:0.0 A EVSE0[2]:13.8 A EVSE1[0]:0.0 A EVSE2[0]:0.0 A EVSE3[0]:0.0 A
STATE: C Error: 0 StartCurrent: -4 ImeasuredNegative: 0.0 A ChargeDelay: 0 SolarStopTimer: 0 NoCurrent: 0 Imeas: 19.4 A IsetBalanced: 13.8 A L1: 19.4 A L2: 0.0 A L3: 0.0 A Isum: 19.4 A
Imeasured:19.4 A IsetBalanced:13.9 A Baseload:0.0 A EVSE0[2]:13.9 A EVSE1[0]:0.0 A EVSE2[0]:0.0 A EVSE3[0]:0.0 A
STATE: C Error: 0 StartCurrent: -4 ImeasuredNegative: 0.0 A ChargeDelay: 0 SolarStopTimer: 0 NoCurrent: 0 Imeas: 19.4 A IsetBalanced: 13.9 A L1: 19.5 A L2: -0.0 A L3: -0.0 A Isum: 19.5 A
Imeasured:19.1 A IsetBalanced:14.1 A Baseload:0.0 A EVSE0[2]:14.1 A EVSE1[0]:0.0 A EVSE2[0]:0.0 A EVSE3[0]:0.0 A
STATE: C Error: 0 StartCurrent: -4 ImeasuredNegative: 0.0 A ChargeDelay: 0 SolarStopTimer: 0 NoCurrent: 0 Imeas: 19.1 A IsetBalanced: 14.1 A L1: 19.1 A L2: -0.0 A L3: 0.0 A Isum: 19.1 A
Imeasured:18.9 A IsetBalanced:14.3 A Baseload:0.0 A EVSE0[2]:14.3 A EVSE1[0]:0.0 A EVSE2[0]:0.0 A EVSE3[0]:0.0 A
STATE: C Error: 0 StartCurrent: -4 ImeasuredNegative: 0.0 A ChargeDelay: 0 SolarStopTimer: 0 NoCurrent: 0 Imeas: 18.9 A IsetBalanced: 14.3 A L1: 19.0 A L2: -0.0 A L3: 0.0 A Isum: 19.0 A
Imeasured:19.0 A IsetBalanced:14.5 A Baseload:0.0 A EVSE0[2]:14.5 A EVSE1[0]:0.0 A EVSE2[0]:0.0 A EVSE3[0]:0.0 A
STATE: C Error: 0 StartCurrent: -4 ImeasuredNegative: 0.0 A ChargeDelay: 0 SolarStopTimer: 0 NoCurrent: 0 Imeas: 19.0 A IsetBalanced: 14.5 A L1: 19.1 A L2: -0.0 A L3: 0.0 A Isum: 19.1 A
````

it looks like that something goes wrong with the data from the smart meter because I am not using a 3 phase connection (yet). 
I'm not that great with microcontroller code so I did not further investigate if the problem lies within the decoding of the modbus data or that the sensorbox is not sending the correct data.

but I think that the load-balancing breaks on the fact that the values are so high that it cannot be put into the Imeasuered signed int. (or at least the seem incompatible)
but since the numbers are higher then the previous values it does try to overwrite them.

It might be a good idea to do a sanity check on the data that is coming in, as it is quite dangerous that the car keeps charging while it does not know the correct current.

please let me know if you want me to debug anything on the smartevse or P1 port!
(i not too confident with embedded C programming (especially when it comes to pointers))

**Comment by mstegen** [comment] 2020-06-15 18:01
This was caused by the sensorbox expecting three phase data from the smartmeter. This is now fixed. As it will check if the data is available, and if it's valid.

**Closed as completed** 2020-06-27 19:02 UTC
